# Generated by Django 6.0 on 2025-12-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="avatar",
            field=models.CharField(
                choices=[
                    ("avatar1.svg", "Avatar 1"),
                    ("avatar2.svg", "Avatar 2"),
                    ("avatar3.svg", "Avatar 3"),
                    ("avatar4.svg", "Avatar 4"),
                    ("avatar5.svg", "Avatar 5"),
                    ("avatar6.svg", "Avatar 6"),
                    ("avatar7.svg", "Avatar 7"),
                    ("avatar8.svg", "Avatar 8"),
                    ("avatar9.svg", "Avatar 9"),
                    ("avatar10.svg", "Avatar 10"),
                ],
                default="avatar1.svg",
                max_length=30,
            ),
        ),
    ]
